---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: realtimeapp-infra
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/sosotechnologies/realtimeapp-infra
